module.exports={
    ADMIN_COLLECTION:"admin",
    JOB_SEEKER_COLLECTION:"jobseeker",
    EMPLOYER_COLLECTION:"employer",
    JOB_SEEKER_JOB_COLLECTION:"jobcollection",
    EMPLOYER_JOB_COLLECTION:"employjobcollection",
    JOBS:'jobs',
    APPLIED_COLLECTION:'appliedcollection'
}